-- Disable RLS on public tables to allow read access
ALTER TABLE collections DISABLE ROW LEVEL SECURITY;
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE product_variants DISABLE ROW LEVEL SECURITY;
ALTER TABLE blogs DISABLE ROW LEVEL SECURITY;
ALTER TABLE homepage_sections DISABLE ROW LEVEL SECURITY;
ALTER TABLE navbar_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE footer_config DISABLE ROW LEVEL SECURITY;
ALTER TABLE website_settings DISABLE ROW LEVEL SECURITY;
